// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package dev.farhan.movieist.movies;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import dev.farhan.movieist.movies.Movie;
import dev.farhan.movieist.movies.MovieRepository;
import dev.farhan.movieist.movies.MovieService;

public class MovieService_findAllMovies_b58cc00632_Test {

    @InjectMocks
    private MovieService movieService;

    @Mock
    private MovieRepository repository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }
    
    @Test
    public void testFindAllMovies() {
        Movie movie1 = new Movie();
        Movie movie2 = new Movie();
        when(repository.findAll()).thenReturn(Arrays.asList(movie1, movie2));
        
        List<Movie> result = movieService.findAllMovies();
        assertNotNull(result);
        assertEquals(2, result.size());
    }

    @Test
    public void testFindAllMoviesNoMovies() {
        when(repository.findAll()).thenReturn(Arrays.asList());
        
        List<Movie> result = movieService.findAllMovies();
        assertNotNull(result);
        assertTrue(result.isEmpty());
    }
}
