// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package dev.farhan.movieist.movies;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.LocalDateTime;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "reviews")
class Review {
    private ObjectId id;
    private String body;
    private LocalDateTime created;
    private LocalDateTime updated;
}

public class Review_Review_ad65a1e26a_Test {
    
    private Review review;
    
    @BeforeEach
    public void setUp() {
        review = new Review();
    }

    @Test
    public void testReviewConstructor_withValidParameters() {
        LocalDateTime created = LocalDateTime.now();
        LocalDateTime updated = LocalDateTime.now();
        review = new Review(null, "This is a test review", created, updated);

        assertEquals("This is a test review", review.getBody());
        assertNotNull(review.getCreated());
        assertNotNull(review.getUpdated());
    }

    @Test
    public void testReviewConstructor_withNullParameters() {
        LocalDateTime created = null;
        LocalDateTime updated = null;
        review = new Review(null, null, created, updated);

        assertNull(review.getBody());
        assertNull(review.getCreated());
        assertNull(review.getUpdated());
    }

}
