// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

package dev.farhan.movieist;

import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.anyString;

public class MovieistApplication_corsConfigurer_7322b2b140_Test {

    @InjectMocks
    MovieistApplication movieistApplication;

    @Mock
    CorsRegistry corsRegistry;

    @Test
    public void testCorsConfigurer() {
        WebMvcConfigurer webMvcConfigurer = movieistApplication.corsConfigurer();
        webMvcConfigurer.addCorsMappings(corsRegistry);

        verify(corsRegistry, times(1)).addMapping(anyString()).allowedOrigins(anyString());
        verify(corsRegistry, times(1)).addMapping(anyString()).allowedMethods(anyString());
        verify(corsRegistry, times(1)).addMapping(anyString()).allowedHeaders(anyString());
        verify(corsRegistry, times(1)).addMapping(anyString()).allowCredentials(false);
        verify(corsRegistry, times(1)).addMapping(anyString()).maxAge(3600);
    }
}
